// <auto-generated />
namespace PROG5ASSESMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changedsomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedsomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201501070217443_changedsomething"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
